services:
  mariadb:
    container_name: mariadb
    image: docker.io/bitnami/mariadb:11.3
    ports:
      - '3306:3306'
    environment:
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=bitnami
    volumes:
      - 'mariadb_data:/bitnami'
  
  phpmyadmin:
    container_name: phpmyadmin
    image: docker.io/bitnami/phpmyadmin:5
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      PMA_HOST: 'db'
      PMA_USER: 'root'
      PMA_PASSWORD: 'bitnami'
    depends_on:
      - mariadb
    
  # Symfony apache project container
  www:
    build: docker/php
    container_name: tutorial_symfony
    ports:
      - "8741:80"
    volumes:
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always

volumes:
  mariadb_data:
    driver: local